from games.beauty_vote.server.constants import (
    CONSECUTIVE_NO_ELIMINATION_LIMIT,
    DOMAIN_INDEPENDENT,
    DOMAIN_TARGET_VALUE,
    DOMAIN_WIN_LOSS_ALT,
    INITIAL_SCORE,
    MAX_PLAYERS,
    MIN_PLAYERS,
    NUMBER_RANGE,
    RULE_META,
    SPECIAL_EVENT_TYPES,
)

__all__ = [
    "INITIAL_SCORE",
    "MIN_PLAYERS",
    "MAX_PLAYERS",
    "NUMBER_RANGE",
    "DOMAIN_INDEPENDENT",
    "DOMAIN_TARGET_VALUE",
    "DOMAIN_WIN_LOSS_ALT",
    "RULE_META",
    "SPECIAL_EVENT_TYPES",
    "CONSECUTIVE_NO_ELIMINATION_LIMIT",
]
